# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "StrehlerSite"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT


engines:
    template:
        template_toolkit:
            ENCODING: utf8
            DEFAULT: 'no.tt'
template: "template_toolkit"

# template: "template_toolkit"
# engines:
#   template:
#     template_toolkit:
#       start_tag: '<%'
#       end_tag:   '%>'

Strehler:
    default_entity: markdown
    languages: ['en']
    default_language: 'en'
    timezone: 'Europe/Rome'
    extra_menu:
        markdown:
            label: markdown
            class: StrehlerSite::Element::MarkdownArticle
            visible: 0
    dashboard_active: 1
    dashboard:
        - type: list
          title: "News"
          category: news
        - type: list
          title: "Releases"
          category: releases
        - type: list
          title: "TODO"
          category: todo
          by: order
        - type: list
          title: "Other Projects"
          category: other-projects
          by: order
        
